// <auto-generated />
using FragranceStoreAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace fragranceAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210805072026_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("FragranceStoreAPI.Model.Fragrance", b =>
                {
                    b.Property<string>("productId")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("brandName")
                        .HasColumnType("text");

                    b.Property<string>("numberOfReviews")
                        .HasColumnType("text");

                    b.Property<string>("productImage")
                        .HasColumnType("text");

                    b.Property<string>("productName")
                        .HasColumnType("text");

                    b.Property<string>("productPrice")
                        .HasColumnType("text");

                    b.Property<string>("productRating")
                        .HasColumnType("text");

                    b.Property<string>("reviewContent")
                        .HasColumnType("text");

                    b.HasKey("productId");

                    b.ToTable("fragrances");
                });
#pragma warning restore 612, 618
        }
    }
}
